import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useAuth } from '../auth/AuthContext'
import { ConfirmDialog, EmptyState, ErrorState, LoadingState, PageHeader, Pagination, StatusBadge } from '../components/ui'
import { api, queryString } from '../lib/api'
import type { Knowledge, KnowledgeDetail, Page } from '../types'

export function KnowledgePage() {
  const { token } = useAuth(); const client = useQueryClient(); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<string | null>(null); const [editor, setEditor] = useState(false); const [archive, setArchive] = useState<string | null>(null)
  const [title, setTitle] = useState(''); const [language, setLanguage] = useState('ar'); const [content, setContent] = useState('')
  const list = useQuery({ queryKey: ['knowledge', page, search], queryFn: () => api<Page<Knowledge>>(`/admin/knowledge${queryString({ page, page_size: 20, search: search.length >= 2 ? search : '' })}`, { token }) })
  const detail = useQuery({ queryKey: ['knowledge-detail', selected], queryFn: () => api<KnowledgeDetail>(`/admin/knowledge/${selected}`, { token }), enabled: Boolean(selected) })
  const invalidate = async () => { await client.invalidateQueries({ queryKey: ['knowledge'] }); if (selected) await client.invalidateQueries({ queryKey: ['knowledge-detail', selected] }) }
  const create = useMutation({ mutationFn: () => api('/admin/knowledge', { method: 'POST', token, body: { title, language, source_format: 'plain_text', content } }), onSuccess: async () => { setEditor(false); setTitle(''); setContent(''); await invalidate() } })
  const approve = useMutation({ mutationFn: ({ document, revision }: { document: string; revision: string }) => api(`/admin/knowledge/${document}/revisions/${revision}/approve`, { method: 'POST', token }), onSuccess: invalidate })
  const archiveMutation = useMutation({ mutationFn: (id: string) => api(`/admin/knowledge/${id}`, { method: 'DELETE', token }), onSuccess: async () => { setArchive(null); setSelected(null); await invalidate() } })
  const reindex = useMutation({ mutationFn: () => api<{ chunk_count: number }>('/admin/knowledge/reindex', { method: 'POST', token }) })
  function submit(event: FormEvent) { event.preventDefault(); create.mutate() }
  return <>
    <PageHeader eyebrow="GROUNDING CONTROL" title="قاعدة المعرفة" description="أنشئ المحتوى الفندقي، راجع النسخ، واعتمد فقط ما يصلح لتغذية إجابات RAG." action={<div className="action-row"><button className="button secondary" onClick={() => reindex.mutate()} disabled={reindex.isPending}>إعادة بناء FAISS</button><button className="button" onClick={() => setEditor(true)}>+ مستند جديد</button></div>} />
    {(create.error || approve.error || archiveMutation.error || reindex.error) && <ErrorState error={create.error ?? approve.error ?? archiveMutation.error ?? reindex.error} />}
    {reindex.isSuccess && <div className="success-banner" role="status">بدأت عملية الفهرسة بنجاح ({reindex.data.chunk_count} chunks).</div>}
    <section className="panel filters"><label className="search-field"><span aria-hidden="true">⌕</span><span className="sr-only">Search</span><input placeholder="ابحث في العناوين…" value={search} onChange={e => { setSearch(e.target.value); setPage(1) }} /></label></section>
    {list.isLoading ? <LoadingState /> : list.error ? <ErrorState error={list.error} retry={() => void list.refetch()} /> : !list.data?.items.length ? <EmptyState /> : <section className="knowledge-layout"><div className="panel knowledge-list">{list.data.items.map(item => <button key={item.id} className={selected === item.id ? 'selected' : ''} onClick={() => setSelected(item.id)}><span><strong>{item.title}</strong><small>{item.language.toUpperCase()} · {item.revision_count} revisions</small></span><StatusBadge value={item.status} /></button>)}<Pagination page={list.data.page} pages={list.data.pages} onPage={setPage} /></div>
      <article className="panel knowledge-detail">{!selected ? <EmptyState title="اختر مستنداً" body="ستظهر النسخ ومحتواها هنا." /> : detail.isLoading ? <LoadingState /> : detail.error || !detail.data ? <ErrorState error={detail.error} /> : <><div className="panel-heading"><div><p className="eyebrow">DOCUMENT</p><h2>{detail.data.document.title}</h2></div><button className="button danger subtle" onClick={() => setArchive(selected)}>أرشفة</button></div><div className="revision-list">{detail.data.revisions.map(revision => <details key={revision.id} open={revision.id === detail.data?.document.current_revision_id}><summary><span><strong>Version {revision.version}</strong><small>{new Date(revision.created_at).toLocaleString()}</small></span>{revision.id === detail.data?.document.current_revision_id ? <StatusBadge value="approved" /> : <button className="button small secondary" onClick={event => { event.preventDefault(); approve.mutate({ document: selected, revision: revision.id }) }}>اعتماد</button>}</summary><p>{revision.content}</p><code>SHA · {revision.checksum.slice(0, 16)}…</code></details>)}</div></>}</article>
    </section>}
    {editor && <div className="dialog-backdrop"><form className="dialog editor-dialog" role="dialog" aria-modal="true" aria-labelledby="new-doc-title" onSubmit={submit}><h2 id="new-doc-title">مستند معرفة جديد</h2><label>العنوان<input required minLength={3} maxLength={255} value={title} onChange={e => setTitle(e.target.value)} /></label><label>اللغة<select value={language} onChange={e => setLanguage(e.target.value)}><option value="ar">العربية</option><option value="en">English</option></select></label><label>المحتوى<textarea required minLength={20} maxLength={100000} rows={12} value={content} onChange={e => setContent(e.target.value)} /></label><div className="dialog-actions"><button type="button" className="button secondary" onClick={() => setEditor(false)}>إلغاء</button><button className="button" disabled={create.isPending}>إنشاء نسخة مسودة</button></div></form></div>}
    <ConfirmDialog open={Boolean(archive)} title="أرشفة مستند المعرفة؟" body="سيتوقف المستند عن المشاركة في عمليات الفهرسة المستقبلية. يبقى سجل النسخ محفوظاً للمراجعة." confirmLabel="نعم، أرشفه" danger busy={archiveMutation.isPending} onClose={() => setArchive(null)} onConfirm={() => { if (archive) archiveMutation.mutate(archive) }} />
  </>
}
