"""add_deferred_foreign_keys

Revision ID: 2b4ece01b94b
Revises: 6fce2a33eb60
Create Date: 2026-07-13 14:09:22.055441
"""

from collections.abc import Sequence

from alembic import op

revision: str = "2b4ece01b94b"
down_revision: str | None = "6fce2a33eb60"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_conversations_summary_message",
        "conversations",
        "messages",
        ["summary_through_message_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_knowledge_documents_current_revision",
        "knowledge_documents",
        "knowledge_revisions",
        ["current_revision_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_knowledge_documents_current_revision", "knowledge_documents", type_="foreignkey"
    )
    op.drop_constraint("fk_conversations_summary_message", "conversations", type_="foreignkey")
    # ### end Alembic commands ###
